In [99]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
data=pd.read_csv("final_data.csv")
#final_data is the final pre processed data

In [100]:
data.head()

Operator In Out Travelling Network Type  Rating Call Drop Category  \
0    Airtel            Indoor           4G       3       Satisfactory   
1  Vodafone            Indoor           4G       1       Call Dropped   
2    Airtel            Indoor           3G       1       Call Dropped   
3    Airtel            Indoor           4G       3       Satisfactory   
4    Airtel        Travelling           4G       3       Satisfactory   

   Latitude  Longitude   State Name  Average Data Speed Download  \
0  0.196228   0.325356    Karnataka                     0.271480   
1  0.632907   0.135432      Gujarat                     0.211519   
2  0.127093   0.290671   Tamil Nadu                     0.036321   
3  0.580181   0.155327      Gujarat                     0.175517   
4  0.425737   0.180503  Maharashtra                     0.333021   

   Average Data Speed Upload  Population  Literacy Rate  Rainfall  \
0                   0.197512           2              7         3   
1                   0.370879           2              8         2   
2                   0.062303           2              8         2   
3                   0.191200           2              8         2   
4                   0.395612           4              8         4   

   Area of the state  Average_Signal  
0           0.504087        0.476721  
1           0.518040        0.477252  
2           0.300607        0.478454  
3           0.518040        0.477699  
4           0.886194        0.476859

In [3]:
Airtel=data[data['Operator']=='Airtel']

In [4]:
Airtel.count()

Unnamed: 0                     6959
Operator                       6959
In Out Travelling              6959
Network Type                   6959
Rating                         6959
Call Drop Category             6959
Latitude                       6959
Longitude                      6959
State Name                     6959
Average Data Speed Download    6959
Average Data Speed Upload      6959
Population                     6959
Literacy Rate                  6959
Rainfall                       6959
Area of the state              6959
Average_Signal                 6959
dtype: int64

In [5]:
from sklearn import preprocessing
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression

In [6]:
X=Airtel[['Latitude','Longitude']]

In [7]:
X.count()

Latitude     6959
Longitude    6959
dtype: int64

In [8]:
y=Airtel['Average Data Speed Download']

In [9]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
#We have used holdout method and 70%of data is taken as training data and rest as testing 

In [10]:
x_train.head()

Latitude  Longitude
0  0.770359   0.444979
1  0.769911   0.451458
2  0.448364   0.146543
3  0.390108   0.188179
4  0.447014   0.146920

In [11]:
n=x_train.count()[0]

In [12]:
n

4871

# Download Data Speed Latitude Longitude

In [13]:
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train['Latitude'][i]
    sum_x2=sum_x2+x_train['Longitude'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Latitude'][i]*x_train['Latitude'][i]
    sum_x1x2=sum_x1x2+x_train['Latitude'][i]*x_train['Longitude'][i]
    sum_x2x2=sum_x2x2+x_train['Longitude'][i]*x_train['Longitude'][i]
    sum_x1y1=sum_x1y1+x_train['Latitude'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Longitude'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])

In [14]:
A

array([[4871.        , 2181.92388565, 1513.9500044 ],
       [2181.92388565, 1248.87341302,  673.32238347],
       [1513.9500044 ,  673.32238347,  555.495765  ]])

In [15]:
B

array([1005.98484219,  449.5237988 ,  314.36582305])

In [16]:
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])

In [19]:
W

array([ 0.20203731, -0.00369466,  0.01976455])

In [22]:
y_pred=w0+w1*x_test['Latitude']+w2*x_test['Longitude']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE=np.sqrt(MSE/len(y_test))
RMSE
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.1207994563615342

In [23]:
ybar=y_test.mean()
ybar

0.2031249278745239

In [24]:
SSR=0
SST=0
SSE=0
y_test.count()
#SST is total sum of squares
#SSR is sum of squares due to regression
#SSE is sum of squares due to error

2088

In [30]:
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])

In [31]:
print("Total sum of squares=", SST )

Total sum of squares= 60.98417545739956


In [32]:
print("Sum of squares due to regression =", SSR)

Sum of squares due to regression = 0.07886373592440582


In [33]:
print("Sum of square due to error=", SSE)

Sum of square due to error= 60.938316152643395


Significance Test

F Test


In [34]:
W

array([ 0.20203731, -0.00369466,  0.01976455])

In [35]:
w0=W[0]
w0

0.2020373135972111

In [36]:
w1=W[1]
w2=W[2]


Regression line is y= b0 + b1 * x1 + b2 * x2

b1 is coefficient of x1

b2 is coefficient of x2

H0 : b1=b2=0

Ha : One or both parameters not equal to zero

In [37]:
MSR=SSR/2
MSR

0.03943186796220291

In [38]:
MSE=SSE/(len(y_test)-3)
MSE

0.029227010145152707

In [39]:
F=MSR/MSE

In [40]:
F=MSR/MSE
#The F test is used to determine whether a significant relationship exists between the dependent variable and the set of all the independent variables; hence F test are referred to as  the test for overall significance

In [41]:
len(y_test)-3

2085

F alpha with numerator dof=2 and denominator dof=n-3(=2085) at level of significance=0.05 is equal to 3.00004067

In [42]:
Falpha=3.00004067

In [43]:
F>=Falpha

False

So we accept H0. As H0 is true then T test is not performed.


# Hence we can conclude that Data Speed Download does not depend on Latitude and Longitude significantly for Airtel.

# Upload Data Speed Latitude Longitude

Now doing the same for Data Speed Upload

In [46]:
n=x_train.count()[0]
y=Airtel['Average Data Speed Upload']
X=Airtel[['Latitude','Longitude']]

In [47]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 

In [48]:
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train['Latitude'][i]
    sum_x2=sum_x2+x_train['Longitude'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Latitude'][i]*x_train['Latitude'][i]
    sum_x1x2=sum_x1x2+x_train['Latitude'][i]*x_train['Longitude'][i]
    sum_x2x2=sum_x2x2+x_train['Longitude'][i]*x_train['Longitude'][i]
    sum_x1y1=sum_x1y1+x_train['Latitude'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Longitude'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])

In [49]:
W

array([0.17355878, 0.07030405, 0.03373295])

In [64]:
y_pred=w0+w1*x_test['Latitude']+w2*x_test['Longitude']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE=np.sqrt(MSE/len(y_test))
RMSE
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.1466596920431193

In [65]:
ybar=y_test.mean()
SSR=0
SST=0
SSE=0
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])
print("Total sum of squares=", SST )
print("Sum of squares due to regression =", SSR)
print("Sum of square due to error=", SSE)

Total sum of squares= 45.52796333541861
Sum of squares due to regression = 0.6327732012792442
Sum of square due to error= 44.91092828414124


In [66]:
w0

0.17355877932708164

In [67]:
w1

0.07030404579616922

In [68]:
w2

0.03373294624977374

So linear regression line is y=b0 + b1 * x1 + b2 * x2

b1 is coefficient of x1


b2 is coefficient of x2

H0 : b1=b2=0


Ha : One or both parameters not equal to zero

In [69]:
MSR=SSR/2
MSE=SSE/(len(y_test)-3)
F=MSR/MSE
Falpha=3.00004067

In [70]:
F>=Falpha

True

Hence we reject H0. As both parameters are not equal to zero so we will find out individually about each parameter through t test.

T test for b1

H0 : b1=0

Ha : b1 is not equal to zero

In [71]:
sum=0
m=x_test['Latitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Latitude'][i]-m)**2)
sum

118.03248911222146

In [72]:
import math
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb1=s/x

In [73]:
sb1

0.013508968946155192

In [74]:
t= w1/sb1

In [75]:
t
#t distribution with n − p − 1 degrees of freedom.
#The t test is used to determine whether each of the individual independent variables is significant. A separate t test is conducted for each of the independent variables in the model; hence t tests are called as the test for individual significance. 

5.204249567557009

talpha at dof = n-3 =2085 at 0.05/2=0.25 level of significance is 2.24

In [76]:
talpha=2.243023

In [77]:
t>=talpha

True

Hence we reject the null hypothesis.

T test for b2

H0 : b2=0

Ha : b2 is not equal to zero

In [78]:
sum=0
m=x_test['Longitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Longitude'][i]-m)**2)
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb2=s/x

In [79]:
sb2

0.024231573741799673

In [80]:
t= w2/s

In [81]:
t

0.22984300342500866

In [82]:
t>=talpha

False

Hence we accept the null hypothesis.

# So we can conclude that Data Speed Upload does depend on Latitude but not on Longitude significantly for Airtel.

# Signal Strength Latitude Longitude

In [83]:
n=x_train.count()[0]
y=Airtel['Average_Signal']
X=Airtel[['Latitude','Longitude']]
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train['Latitude'][i]
    sum_x2=sum_x2+x_train['Longitude'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Latitude'][i]*x_train['Latitude'][i]
    sum_x1x2=sum_x1x2+x_train['Latitude'][i]*x_train['Longitude'][i]
    sum_x2x2=sum_x2x2+x_train['Longitude'][i]*x_train['Longitude'][i]
    sum_x1y1=sum_x1y1+x_train['Latitude'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Longitude'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])
W

array([ 0.47765905,  0.00051614, -0.00140833])

In [84]:
y_pred=w0+w1*x_test['Latitude']+w2*x_test['Longitude']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE=np.sqrt(MSE/len(y_test))
RMSE
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.0009050759859348886

In [85]:
ybar=y_test.mean()
SSR=0
SST=0
SSE=0
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])
print("Total sum of squares=", SST )
print("Sum of squares due to regression =", SSR)
print("Sum of square due to error=", SSE)

Total sum of squares= 0.0018104392620998605
Sum of squares due to regression = 0.00010725338399373709
Sum of square due to error= 0.0017104113841798303


So linear regression line is y=b0 + b1 * x1 + b2 * x2

F test

H0 : b1=b2=0


Ha : One or both parameters not equal to zero

In [86]:
MSR=SSR/2
MSE=SSE/(len(y_test)-3)
F=MSR/MSE
Falpha=3.00003861

In [87]:
F

65.37120475673541

In [88]:
F>=Falpha

True

Hence we reject H0. As both parameters are not equal to zero so we will find out individually about each parameter through t test.

T test for b1

H0 : b1=0


Ha : b1 is not equal to zero


In [89]:
sum=0
m=x_test['Latitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Latitude'][i]-m)**2)
sum

118.03248911222146

In [90]:
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb1=s/x

In [91]:
sb1

8.336744212111437e-05

In [92]:
t=w1/sb1

In [93]:
talpha


2.243023

In [94]:
w1

0.0005161395627242826

In [95]:
t>=talpha

True

Hence we reject null hypothesis

T test for b2

H0 : b2=0

Ha : b2 is not equal to zero

In [96]:
sum=0
m=x_test['Longitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Longitude'][i]-m)**2)
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb2=s/x
t=w2/sb2

In [97]:
t

-9.417812542349603

In [98]:
t<=-talpha

True

Hence we reject null hypothesis

# Hence we can conclude that Signal Strength does depend on Latitude and Longitude significantly for Airtel.

In [ ]:
#For download data speed there does not exist a significant relationship with latitude and longitude.
#For upload data speed there exists a significant relationship with latitude only.
#For signal strength also there exists a significant relationship with latitude and longitude.
