In [40]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
data=pd.read_csv("final_data.csv")
#final_data is the final pre processed data

In [41]:
data.head()

Operator In Out Travelling Network Type  Rating Call Drop Category  \
0    Airtel            Indoor           4G       3       Satisfactory   
1  Vodafone            Indoor           4G       1       Call Dropped   
2    Airtel            Indoor           3G       1       Call Dropped   
3    Airtel            Indoor           4G       3       Satisfactory   
4    Airtel        Travelling           4G       3       Satisfactory   

   Latitude  Longitude   State Name  Average Data Speed Download  \
0  0.196228   0.325356    Karnataka                     0.271480   
1  0.632907   0.135432      Gujarat                     0.211519   
2  0.127093   0.290671   Tamil Nadu                     0.036321   
3  0.580181   0.155327      Gujarat                     0.175517   
4  0.425737   0.180503  Maharashtra                     0.333021   

   Average Data Speed Upload  Population  Literacy Rate  Rainfall  \
0                   0.197512           2              7         3   
1                   0.370879           2              8         2   
2                   0.062303           2              8         2   
3                   0.191200           2              8         2   
4                   0.395612           4              8         4   

   Area of the state  Average_Signal  
0           0.504087        0.476721  
1           0.518040        0.477252  
2           0.300607        0.478454  
3           0.518040        0.477699  
4           0.886194        0.476859

In [42]:
Airtel=data[data['Operator']=='Airtel']

In [43]:
Airtel.count()

Operator                       6959
In Out Travelling              6959
Network Type                   6959
Rating                         6959
Call Drop Category             6959
Latitude                       6959
Longitude                      6959
State Name                     6959
Average Data Speed Download    6959
Average Data Speed Upload      6959
Population                     6959
Literacy Rate                  6959
Rainfall                       6959
Area of the state              6959
Average_Signal                 6959
dtype: int64

In [44]:
from sklearn import preprocessing
from numpy.linalg import inv

In [45]:
X=Airtel[['Average Data Speed Download','Average Data Speed Upload']]

In [46]:
X.count()

Average Data Speed Download    6959
Average Data Speed Upload      6959
dtype: int64

In [47]:
y=Airtel['Average_Signal']

In [48]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
#We have used holdout method and 70%of data is taken as training data and rest as testing 

In [49]:
x_train.head()

Average Data Speed Download  Average Data Speed Upload
0                     0.227598                   0.407192
1                     0.227598                   0.407192
2                     0.057104                   0.027342
3                     0.057104                   0.027342
4                     0.057104                   0.027342

In [50]:
n=x_train.count()[0]

In [51]:
n

4871

# Regression model of degree 1

In [52]:
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train['Average Data Speed Download'][i]
    sum_x2=sum_x2+x_train['Average Data Speed Upload'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Download'][i]
    sum_x1x2=sum_x1x2+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Upload'][i]
    sum_x2x2=sum_x2x2+x_train['Average Data Speed Upload'][i]*x_train['Average Data Speed Upload'][i]
    sum_x1y1=sum_x1y1+x_train['Average Data Speed Download'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Average Data Speed Upload'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2)

In [53]:
A

array([[4871.        , 1005.98484219, 1049.87288501],
       [1005.98484219,  279.58003418,  298.16972767],
       [1049.87288501,  298.16972767,  333.59914555]])

In [54]:
B

array([2325.67127624,  479.82722399,  500.73166046])

In [55]:
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])

In [56]:
W

array([ 0.47885782, -0.00776782,  0.00092312])

In [57]:
y_pred=w0+w1*x_test['Average Data Speed Download']+w2*x_test['Average Data Speed Upload']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE1=np.sqrt(MSE/len(y_test))
RMSE1
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.00042421277132492324

In [58]:
ybar=y_test.mean()
ybar

0.4774672253721212

In [60]:
SSR=0
SST=0
SSE=0
y_test.count()
#SST is total sum of squares
#SSR is sum of squares due to regression
#SSE is sum of squares due to error

2088

In [61]:
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])

In [62]:
print("Total sum of squares=", SST )

Total sum of squares= 0.001810439559007167


In [63]:
print("Sum of squares due to regression =", SSR)

Sum of squares due to regression = 0.0013822933869873893


In [64]:
print("Sum of square due to error=", SSE)

Sum of square due to error= 0.0003757491205415984


In [65]:
Rsquare=SSR/SST

In [66]:
print("R square value=",Rsquare)

R square value= 0.7635125846153239


Since there are 2 independent variable so R square adjusted is also calculated. 

In [67]:
p=2
n=len(y_test)


In [68]:
Rsquare_adjusted=1-(((1-Rsquare)*(n-1))/(n-p-1))

In [69]:
Rsquare_adjusted

0.7632857381737079

Significance Test

F Test


In [70]:
W

array([ 0.47885782, -0.00776782,  0.00092312])

In [71]:
w0=W[0]
w0

0.47885781860523335

In [72]:
w1=W[1]
w2=W[2]


Regression line is y= b0 + b1 * x1 + b2 * x2

b1 is coefficient of x1

b2 is coefficient of x2

H0 : b1=b2=0

Ha : One or both parameters not equal to zero

In [73]:
MSR=SSR/2
MSR

0.0006911466934936947

In [74]:
MSE=SSE/(len(y_test)-3)
MSE

1.802154055355388e-07

In [75]:
F=MSR/MSE
#The F test is used to determine whether a significant relationship exists between the dependent variable and the set of all the independent variables; hence F test are referred to as  the test for overall significance

In [76]:
F

3835.114381258595

In [77]:
len(y_test)-3

2085

F alpha with numerator dof=2 and denominator dof=n-3(=2085) at level of significance=0.05 is equal to 3.00004067

In [78]:
Falpha=3.00004067

In [79]:
F>=Falpha

True

So we reject H0. As H0 is false then T test is performed.


Hence we reject H0. As both parameters are not equal to zero so we will find out individually about each parameter through t test.

T test for b1

H0 : b1=0

Ha : b1 is not equal to zero

In [80]:
sum=0
m=x_test['Average Data Speed Download'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Average Data Speed Download'][i]-m)**2)
sum

30.492087728700483

In [81]:
import math
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb1=s/x

In [82]:
sb1

7.687805308743059e-05

In [83]:
t= w1/sb1

In [84]:
t
#t distribution with n − p − 1 degrees of freedom.
#The t test is used to determine whether each of the individual independent variables is significant. A separate t test is conducted for each of the independent variables in the model; hence t tests are called as the test for individual significance. 

-101.04086203812982

talpha at dof = n-3 =2085 at 0.05/2=0.25 level of significance is 2.24

In [85]:
talpha=2.243023

In [86]:
t<=-talpha

True

Hence we reject the null hypothesis.

T test for b2

H0 : b2=0

Ha : b2 is not equal to zero

In [87]:
sum=0
m=x_test['Average Data Speed Upload'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Average Data Speed Upload'][i]-m)**2)
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb2=s/x

In [88]:
sb2

6.291538308278185e-05

In [89]:
t= w2/s

In [90]:
t

2.1745075167190193

In [91]:
t>=talpha

False

Hence we accept the null hypothesis.

# So we can conclude that Signal Strength does depend on Download Speed but not on Upload Speed significantly for Airtel.