In [12]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
data=pd.read_csv("final_data.csv")
#final_data is the final pre processed data

In [13]:
data.head()

Operator In Out Travelling Network Type  Rating Call Drop Category  \
0    Airtel            Indoor           4G       3       Satisfactory   
1  Vodafone            Indoor           4G       1       Call Dropped   
2    Airtel            Indoor           3G       1       Call Dropped   
3    Airtel            Indoor           4G       3       Satisfactory   
4    Airtel        Travelling           4G       3       Satisfactory   

   Latitude  Longitude   State Name  Average Data Speed Download  \
0  0.196228   0.325356    Karnataka                     0.271480   
1  0.632907   0.135432      Gujarat                     0.211519   
2  0.127093   0.290671   Tamil Nadu                     0.036321   
3  0.580181   0.155327      Gujarat                     0.175517   
4  0.425737   0.180503  Maharashtra                     0.333021   

   Average Data Speed Upload  Population  Literacy Rate  Rainfall  \
0                   0.197512           2              7         3   
1                   0.370879           2              8         2   
2                   0.062303           2              8         2   
3                   0.191200           2              8         2   
4                   0.395612           4              8         4   

   Area of the state  Average_Signal  
0           0.504087        0.476721  
1           0.518040        0.477252  
2           0.300607        0.478454  
3           0.518040        0.477699  
4           0.886194        0.476859

In [14]:
data['Operator'].unique()

array(['Airtel', 'Vodafone', 'RJio', 'BSNL', 'Idea'], dtype=object)

In [15]:
BSNL=data[data['Operator']=='BSNL']

In [16]:
BSNL.count()

Operator                       609
In Out Travelling              609
Network Type                   609
Rating                         609
Call Drop Category             609
Latitude                       609
Longitude                      609
State Name                     609
Average Data Speed Download    609
Average Data Speed Upload      609
Population                     609
Literacy Rate                  609
Rainfall                       609
Area of the state              609
Average_Signal                 609
dtype: int64

In [19]:
from sklearn import preprocessing
from numpy.linalg import inv

In [20]:
X=BSNL[['Average Data Speed Download','Average Data Speed Upload']]

In [21]:
X.count()

Average Data Speed Download    609
Average Data Speed Upload      609
dtype: int64

In [22]:
y=BSNL['Average_Signal']

In [24]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
#We have used holdout method and 70%of data is taken as training data and rest as testing 

In [25]:
x_train.head()

Average Data Speed Download  Average Data Speed Upload
0                     0.070379                   0.074957
1                     0.070379                   0.074957
2                     0.098693                   0.108892
3                     0.298309                   0.266938
4                     0.098693                   0.108892

In [26]:
n=x_train.count()[0]

In [27]:
n

426

# Regression model of degree 1

In [28]:
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train['Average Data Speed Download'][i]
    sum_x2=sum_x2+x_train['Average Data Speed Upload'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Download'][i]
    sum_x1x2=sum_x1x2+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Upload'][i]
    sum_x2x2=sum_x2x2+x_train['Average Data Speed Upload'][i]*x_train['Average Data Speed Upload'][i]
    sum_x1y1=sum_x1y1+x_train['Average Data Speed Download'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Average Data Speed Upload'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2)

In [29]:
A

array([[426.        ,  34.1635188 ,  45.59298679],
       [ 34.1635188 ,   4.27197393,   4.76631905],
       [ 45.59298679,   4.76631905,   7.16973132]])

In [30]:
B

array([203.97253781,  16.35883236,  21.81456585])

In [31]:
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])

In [32]:
W

array([ 0.47929795,  0.00872661, -0.01110966])

In [34]:
y_pred=w0+w1*x_test['Average Data Speed Download']+w2*x_test['Average Data Speed Upload']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE1=np.sqrt(MSE/len(y_test))
RMSE1
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.000732876687258436

In [35]:
ybar=y_test.mean()
ybar

0.4789277980273223

In [37]:
SSR=0
SST=0
SSE=0
y_test.count()
#SST is total sum of squares
#SSR is sum of squares due to regression
#SSE is sum of squares due to error

183

In [38]:
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])    

In [39]:
print("Total sum of squares=", SST )

Total sum of squares= 0.0001557397741875759


In [40]:
print("Sum of squares due to regression =", SSR)

Sum of squares due to regression = 5.7863937255452094e-05


In [41]:
print("Sum of square due to error=", SSE)

Sum of square due to error= 9.829080768702258e-05


In [42]:
Rsquare=SSR/SST

In [43]:
print("R square value=",Rsquare)

R square value= 0.3715424499444804


Since there are 2 independent variable so R square adjusted is also calculated. 

In [44]:
p=2
n=len(y_test)
len(x_train)+len(x_test)

609

In [45]:
Rsquare_adjusted=1-(((1-Rsquare)*(n-1))/(n-p-1))

In [46]:
Rsquare_adjusted

0.3645595882771968

Significance Test

F Test


In [47]:
W

array([ 0.47929795,  0.00872661, -0.01110966])

In [48]:
w0=W[0]
w0

0.47929795451696366

In [49]:
w1=W[1]
w2=W[2]


Regression line is y= b0 + b1 * x1 + b2 * x2

b1 is coefficient of x1

b2 is coefficient of x2

H0 : b1=b2=0

Ha : One or both parameters not equal to zero

In [50]:
MSR=SSR/2
MSR

2.8931968627726047e-05

In [51]:
MSE=SSE/(len(y_test)-3)
MSE

5.46060042705681e-07

In [53]:
F=MSR/MSE
#The F test is used to determine whether a significant relationship exists between the dependent variable and the set of all the independent variables; hence F test are referred to as  the test for overall significance

In [54]:
F

52.983127064874786

In [55]:
len(y_test)-3

180

F alpha with numerator dof=2 and denominator dof=n-3 at level of significance=0.05

In [56]:
Falpha=3.04614794

In [57]:
F>=Falpha

True

So we reject H0. Now for b1 and b2 t tests are performed separately.


T test for b1

H0 : b1=0

Ha : b1 is not equal to zero

In [58]:
sum=0
m=x_test['Average Data Speed Download'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Average Data Speed Download'][i]-m)**2)
sum

0.4759943130771605

In [59]:
import math
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb1=s/x

In [60]:
t=w1/sb1

In [63]:
t
#t distribution with n − p − 1 degrees of freedom.
#The t test is used to determine whether each of the individual independent variables is significant. A separate t test is conducted for each of the independent variables in the model; hence t tests are called as the test for individual significance. 

8.147538549465246

In [64]:
len(y_test)-3

180

So talpha=2.26 at dof=len(y_test)-3 and alpha=0.025

In [65]:
talpha=2.260307
t>=talpha

True

Hence we reject null hypothesis

T Test for b2

H0 : b2=0

Ha : b2 not equal to zero

In [66]:
sum=0
m=x_test['Average Data Speed Upload'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Average Data Speed Upload'][i]-m)**2)
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb2=s/x

In [67]:
t=w2/sb2

In [68]:
t

-12.85838911765779

In [69]:
t<=-talpha

True

Hence we reject null hypothesis

# Hence we can conclude that Signal Strength does depend on Download and Upload Speed significantly for BSNL