In [1]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
data=pd.read_csv("final_data.csv")
#final_data is the final pre processed data

In [2]:
data.head()

Operator In Out Travelling Network Type  Rating Call Drop Category  \
0    Airtel            Indoor           4G       3       Satisfactory   
1  Vodafone            Indoor           4G       1       Call Dropped   
2    Airtel            Indoor           3G       1       Call Dropped   
3    Airtel            Indoor           4G       3       Satisfactory   
4    Airtel        Travelling           4G       3       Satisfactory   

   Latitude  Longitude   State Name  Average Data Speed Download  \
0  0.196228   0.325356    Karnataka                     0.271480   
1  0.632907   0.135432      Gujarat                     0.211519   
2  0.127093   0.290671   Tamil Nadu                     0.036321   
3  0.580181   0.155327      Gujarat                     0.175517   
4  0.425737   0.180503  Maharashtra                     0.333021   

   Average Data Speed Upload  Population  Literacy Rate  Rainfall  \
0                   0.197512           2              7         3   
1                   0.370879           2              8         2   
2                   0.062303           2              8         2   
3                   0.191200           2              8         2   
4                   0.395612           4              8         4   

   Area of the state  Average_Signal  
0           0.504087        0.476721  
1           0.518040        0.477252  
2           0.300607        0.478454  
3           0.518040        0.477699  
4           0.886194        0.476859

In [3]:
data['Operator'].unique()

array(['Airtel', 'Vodafone', 'RJio', 'BSNL', 'Idea'], dtype=object)

In [4]:
Idea=data[data['Operator']=='Idea']

In [5]:
Idea.count()

Operator                       2034
In Out Travelling              2034
Network Type                   2034
Rating                         2034
Call Drop Category             2034
Latitude                       2034
Longitude                      2034
State Name                     2034
Average Data Speed Download    2034
Average Data Speed Upload      2034
Population                     2034
Literacy Rate                  2034
Rainfall                       2034
Area of the state              2034
Average_Signal                 2034
dtype: int64

In [6]:
from sklearn import preprocessing
from numpy.linalg import inv

In [7]:
X=Idea[['Average Data Speed Download','Average Data Speed Upload']]

In [8]:
X.count()

Average Data Speed Download    2034
Average Data Speed Upload      2034
dtype: int64

In [9]:
y=Idea['Average_Signal']

In [11]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
#We have used holdout method and 70%of data is taken as training data and rest as testing

In [12]:
x_train.head()

Average Data Speed Download  Average Data Speed Upload
0                     0.053707                   0.079390
1                     0.177117                   0.445744
2                     0.099340                   0.149422
3                     0.053707                   0.079390
4                     0.053707                   0.079390

In [13]:
n=x_train.count()[0]

In [14]:
n

1423

# Regression Model

In [15]:
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train['Average Data Speed Download'][i]
    sum_x2=sum_x2+x_train['Average Data Speed Upload'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Download'][i]
    sum_x1x2=sum_x1x2+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Upload'][i]
    sum_x2x2=sum_x2x2+x_train['Average Data Speed Upload'][i]*x_train['Average Data Speed Upload'][i]
    sum_x1y1=sum_x1y1+x_train['Average Data Speed Download'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Average Data Speed Upload'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2)

In [16]:
A

array([[1423.        ,  183.70216724,  401.5040905 ],
       [ 183.70216724,   29.82983644,   68.91339162],
       [ 401.5040905 ,   68.91339162,  164.56474652]])

In [17]:
B

array([679.82767935,  87.70441632, 191.63072536])

In [18]:
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])

In [19]:
W

array([ 0.47845812,  0.00859258, -0.00646742])

In [20]:
y_pred=w0+w1*x_test['Average Data Speed Download']+w2*x_test['Average Data Speed Upload']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE1=np.sqrt(MSE/len(y_test))
RMSE1
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.00041971114219753805

In [21]:
ybar=y_test.mean()
ybar

0.4777159241260216

In [23]:
SSR=0
SST=0
SSE=0
y_test.count()
#SST is total sum of squares
#SSR is sum of squares due to regression
#SSE is sum of squares due to error

611

In [24]:
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])  

In [25]:
print("Total sum of squares=", SST )

Total sum of squares= 0.00040479863709094873


In [26]:
print("Sum of squares due to regression =", SSR)

Sum of squares due to regression = 0.0002977747738228349


In [27]:
print("Sum of square due to error=", SSE)

Sum of square due to error= 0.00010763219760258958


In [28]:
Rsquare=SSR/SST

In [29]:
print("R square value=",Rsquare)

R square value= 0.7356120958379905


Since there are 2 independent variable so R square adjusted is also calculated. 

In [30]:
p=2
n=len(y_test)
len(x_train)+len(x_test)

2034

In [31]:
Rsquare_adjusted=1-(((1-Rsquare)*(n-1))/(n-p-1))

In [32]:
Rsquare_adjusted

0.734742398784826

Significance Test

F Test


In [33]:
W

array([ 0.47845812,  0.00859258, -0.00646742])

In [34]:
w0=W[0]
w0

0.478458115784715

In [35]:
w1=W[1]
w2=W[2]


Regression line is y= b0 + b1 * x1 + b2 * x2

b1 is coefficient of x1

b2 is coefficient of x2

H0 : b1=b2=0

Ha : One or both parameters not equal to zero

In [36]:
MSR=SSR/2
MSR

0.00014888738691141745

In [37]:
MSE=SSE/(len(y_test)-3)
MSE

1.7702664079373287e-07

In [38]:
F=MSR/MSE
#The F test is used to determine whether a significant relationship exists between the dependent variable and the set of all the independent variables; hence F test are referred to as  the test for overall significance

In [39]:
F

841.0450892806434

In [40]:
len(y_test)

611

F alpha with numerator dof=2 and denominator dof=n-3 at level of significance=0.05 is equal to 3.01

In [41]:
Falpha=3.01054142

In [42]:
F>=Falpha

True

So we reject H0. Now for b1 and b2 t tests are performed separately.


T test for b1

H0 : b1=0

Ha : b1 is not equal to zero

In [43]:
sum=0
m=x_test['Average Data Speed Download'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Average Data Speed Download'][i]-m)**2)
sum

2.53502424970822

In [44]:
import math
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb1=s/x

In [45]:
t=w1/sb1

In [46]:
t
#t distribution with n − p − 1 degrees of freedom.
#The t test is used to determine whether each of the individual independent variables is significant. A separate t test is conducted for each of the independent variables in the model; hence t tests are called as the test for individual significance. 

32.51586883164612

In [47]:
len(y_test)-3

608

So talpha=2.246 at dof=len(y_test)-3 and alpha=0.025

In [48]:
talpha=2.246968
t>=talpha

True

Hence we reject null hypothesis

T Test for b2

H0 : b2=0

Ha : b2 not equal to zero

In [49]:
sum=0
m=x_test['Average Data Speed Upload'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Average Data Speed Upload'][i]-m)**2)
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb2=s/x

In [50]:
t=w2/sb2

In [51]:
t

-71.39298724481023

In [52]:
t<=-talpha

True

Hence we reject null hypothesis

# So we can conclude that Signal Strength does depend on Download and Upload Speed significantly for Airtel.