In [275]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
data=pd.read_csv("final_data.csv")
#final_data is the final pre processed data

In [276]:
data.head(5)

Operator In Out Travelling Network Type  Rating Call Drop Category  \
0    Airtel            Indoor           4G       3       Satisfactory   
1  Vodafone            Indoor           4G       1       Call Dropped   
2    Airtel            Indoor           3G       1       Call Dropped   
3    Airtel            Indoor           4G       3       Satisfactory   
4    Airtel        Travelling           4G       3       Satisfactory   

   Latitude  Longitude   State Name  Average Data Speed Download  \
0  0.196228   0.325356    Karnataka                     0.271480   
1  0.632907   0.135432      Gujarat                     0.211519   
2  0.127093   0.290671   Tamil Nadu                     0.036321   
3  0.580181   0.155327      Gujarat                     0.175517   
4  0.425737   0.180503  Maharashtra                     0.333021   

   Average Data Speed Upload  Population  Literacy Rate  Rainfall  \
0                   0.197512           2              7         3   
1                   0.370879           2              8         2   
2                   0.062303           2              8         2   
3                   0.191200           2              8         2   
4                   0.395612           4              8         4   

   Area of the state  Average_Signal  
0           0.504087        0.476721  
1           0.518040        0.477252  
2           0.300607        0.478454  
3           0.518040        0.477699  
4           0.886194        0.476859

In [277]:
data.count()[0]

30715

In [195]:
from sklearn import preprocessing
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression

In [196]:
X=data[['Latitude','Longitude']]

In [197]:
X.count()

Latitude     30715
Longitude    30715
dtype: int64

In [198]:
y=data['Average Data Speed Download']

In [199]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
#We have used holdout method and 70%of data is taken as training data and rest as testing 

In [200]:
x_train.head()

Latitude  Longitude
0  0.498700   0.631606
1  0.451912   0.143607
2  0.871258   0.274259
3  0.594659   0.729902
4  0.193572   0.417718

In [201]:
n=x_train.count()[0]

In [202]:
n

21500

# Download Data Speed Latitude Longitude

In [203]:
sum_x1=0
#sum_x1x1 means summation of x1 for all objects
sum_x2=0
#sum_x2 means summation of x2 for all objects
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
#The sums act as accumulator
for i in range(0,n):
    sum_x1=sum_x1+x_train['Latitude'][i]
    sum_x2=sum_x2+x_train['Longitude'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Latitude'][i]*x_train['Latitude'][i]
    sum_x1x2=sum_x1x2+x_train['Latitude'][i]*x_train['Longitude'][i]
    sum_x2x2=sum_x2x2+x_train['Longitude'][i]*x_train['Longitude'][i]
    sum_x1y1=sum_x1y1+x_train['Latitude'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Longitude'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2)

In [204]:
A

array([[21500.        , 11305.59854537,  6946.46140205],
       [11305.59854537,  6825.95490532,  3754.38127528],
       [ 6946.46140205,  3754.38127528,  2972.37613929]])

In [205]:
B

array([8869.84387229, 4671.89409607, 3171.58142257])

In [206]:
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])

In [207]:
W
#W is the parameter array

array([ 0.29621098, -0.0403033 ,  0.4256787 ])

In [208]:
y_pred=w0+w1*x_test['Latitude']+w2*x_test['Longitude']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE=np.sqrt(MSE/len(y_test))
RMSE
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.2869590015313743

In [209]:
ybar=y_test.mean()
ybar

0.4148969246526277

In [210]:
SSR=0
SST=0
SSE=0
y_test.count()
#SST is total sum of squares
#SSR is sum of squares due to regression
#SSE is sum of squares due to error

9215

In [211]:
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])  

In [212]:
print("Total sum of squares=", SST )

Total sum of squares= 812.4571737593313


In [213]:
print("Sum of squares due to regression =", SSR)

Sum of squares due to regression = 55.71173645743418


In [214]:
print("Sum of square due to error=", SSE)

Sum of square due to error= 758.8134927793246


In [215]:
p=2
n=len(y_test)
len(x_train)+len(x_test)

30715

Significance Test

F Test


In [216]:
W

array([ 0.29621098, -0.0403033 ,  0.4256787 ])

In [217]:
w0=W[0]
w0

0.2962109816026024

In [218]:
w1=W[1]
w2=W[2]

Regression line is y= b0 + b1 * x1 + b2 * x2

b1 is coefficient of x1

b2 is coefficient of x2

H0 : b1=b2=0

Ha : One or both parameters not equal to zero

In [219]:
MSR=SSR/2
MSR

27.85586822871709

In [220]:
MSE=SSE/(len(y_test)-3)
MSE

0.08237228536466833

In [221]:
F=MSR/MSE
#The F test is used to determine whether a significant relationship exists between the dependent variable and the set of all the independent variables; hence F test are referred to as  the test for overall significance

In [222]:
F

338.17039439171873

In [223]:
len(y_test)-3

9212

F alpha with numerator dof=2 and denominator dof=n-3 at level of significance=0.05 is equal to 2.998

In [224]:
Falpha=2.99670669

In [225]:
F>=Falpha
#F distribution with p degrees of freedom in the numerator
#and n − p − 1 degrees of freedom in the denominator

True

So we reject H0. Now for b1 and b2 t tests are performed separately.


T test for b1

H0 : b1=0

Ha : b1 is not equal to zero

In [226]:
sum=0
m=x_test['Latitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Latitude'][i]-m)**2)
sum

380.06632619565886

In [227]:
import math
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb1=s/x

In [228]:
t=w1/sb1

In [229]:
t

-2.737661453786502

In [230]:
len(y_test)-3

9212

So talpha=2.242 at dof=len(y_test)-3 and alpha=0.025

In [231]:
talpha=2.241769
t<=-talpha
#t distribution with n − p − 1 degrees of freedom.
#The t test is used to determine whether each of the individual independent variables is significant. A separate t test is conducted for each of the independent variables in the model; hence t tests are called as the test for individual significance. 

True

Hence we reject null hypothesis

T Test for b2

H0 : b2=0

Ha : b2 not equal to zero

In [232]:
sum=0
m=x_test['Longitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Longitude'][i]-m)**2)
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb2=s/x

In [233]:
t=w2/sb2

In [234]:
t
#The t test is used to determine whether each of the individual independent variables is significant. A separate t test is conducted for each of the independent variables in the model; hence t tests are called as the test for individual significance. 


26.181276051419292

In [235]:
t>=talpha

True

Hence we reject null hypothesis

# Hence we can conclude that Download data speed does depend on Latitude and Longitude significantly

# Upload Data Speed Latitude Longitude

Now doing the same for Data Speed Upload

In [236]:
n=x_train.count()[0]
y=data['Average Data Speed Upload']
X=data[['Latitude','Longitude']]

In [237]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 

In [238]:
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train['Latitude'][i]
    sum_x2=sum_x2+x_train['Longitude'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Latitude'][i]*x_train['Latitude'][i]
    sum_x1x2=sum_x1x2+x_train['Latitude'][i]*x_train['Longitude'][i]
    sum_x2x2=sum_x2x2+x_train['Longitude'][i]*x_train['Longitude'][i]
    sum_x1y1=sum_x1y1+x_train['Latitude'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Longitude'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2)

In [239]:
W


array([ 0.26739609, -0.05137202,  0.21562823])

In [240]:
y_pred=w0+w1*x_test['Latitude']+w2*x_test['Longitude']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE=np.sqrt(MSE/len(y_test))
RMSE
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.16377595747275991

In [241]:
ybar=y_test.mean()
SSR=0
SST=0
SSE=0
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])
print("Total sum of squares=", SST )
print("Sum of squares due to regression =", SSR)
print("Sum of square due to error=", SSE)

Total sum of squares= 261.24187992204867
Sum of squares due to regression = 14.580896230678366
Sum of square due to error= 247.16992952798898


In [242]:
w0

0.2673960910338645

In [243]:
w1

-0.051372018209086934

In [244]:
w2

0.21562823205907344

So linear regression line is y=b0 + b1 * x1 + b2 * x2

b1 is coefficient of x1


b2 is coefficient of x2

H0 : b1=b2=0


Ha : One or both parameters not equal to zero

In [245]:
MSR=SSR/2
MSE=SSE/(len(y_test)-3)
F=MSR/MSE
Falpha=2.99670669
F

271.714314790463

In [246]:
F>=Falpha

True

Hence we reject H0. As both parameters are not equal to zero so we will find out individually about each parameter through t test.

T test for b1

H0 : b1=0

Ha : b1 is not equal to zero

In [247]:
sum=0
m=x_test['Latitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Latitude'][i]-m)**2)
sum

380.06632619565886

In [248]:
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb1=s/x

In [249]:
sb1

0.008402164030904512

In [250]:
t= w1/sb1

In [251]:
t

-6.114141311706411

talpha at dof = n-2 at 0.05/2=0.25 level of significance is 2.24

In [252]:
talpha=2.241769

In [253]:
t<=-talpha

True

Hence we reject the null hypothesis.

T test for b2

H0 : b2=0

Ha : b2 is not equal to zero

In [254]:
sum=0
m=x_test['Longitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Longitude'][i]-m)**2)
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb2=s/x

In [255]:
sb2

0.009279432333714756

In [256]:
t= w2/s

In [257]:
t

1.3163905922412844

In [258]:
t>=talpha

False

Hence we accept the null hypothesis.

# Hence we can conclude that Data Speed Upload does depend on Latitude but not on Longitude significantly.

# Signal Strength Latitude Longitude

In [259]:
n=x_train.count()[0]
y=data['Average_Signal']
X=data[['Latitude','Longitude']]
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train['Latitude'][i]
    sum_x2=sum_x2+x_train['Longitude'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Latitude'][i]*x_train['Latitude'][i]
    sum_x1x2=sum_x1x2+x_train['Latitude'][i]*x_train['Longitude'][i]
    sum_x2x2=sum_x2x2+x_train['Longitude'][i]*x_train['Longitude'][i]
    sum_x1y1=sum_x1y1+x_train['Latitude'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Longitude'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])
W

array([4.77600305e-01, 4.07924288e-04, 5.90384020e-04])

In [260]:
y_pred=w0+w1*x_test['Latitude']+w2*x_test['Longitude']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE=np.sqrt(MSE/len(y_test))
RMSE
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.001040985302475305

In [261]:
ybar=y_test.mean()
SSR=0
SST=0
SSE=0
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])
print("Total sum of squares=", SST )
print("Sum of squares due to regression =", SSR)
print("Sum of square due to error=", SSE)


Total sum of squares= 0.010176870650564574
Sum of squares due to regression = 0.00019304058571094498
Sum of square due to error= 0.00998583843571988


So linear regression line is y=b0 + b1 * x1 + b2 * x2

F test

H0 : b1=b2=0


Ha : One or both parameters not equal to zero

In [262]:
MSR=SSR/2
MSE=SSE/(len(y_test)-3)
F=MSR/MSE
Falpha=2.99670669

In [263]:
F

89.04058918118415

In [264]:
F>=Falpha

True

Hence we reject H0. As both parameters are not equal to zero so we will find out individually about each parameter through t test.

T test for b1

H0 : b1=0


Ha : b1 is not equal to zero


In [265]:
sum=0
m=x_test['Latitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Latitude'][i]-m)**2)
sum

380.06632619565886

In [266]:
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb1=s/x

In [267]:
sb1

5.340545340187084e-05

In [268]:
t=w1/sb1

In [269]:
t

7.63825156157423

In [270]:
w1

0.0004079242878434197

In [271]:
t>=talpha

True

Hence we reject null hypothesis

T test for b2

H0 : b2=0

Ha : b2 is not equal to zero

In [272]:
sum=0
m=x_test['Longitude'].mean()
for i in range(0,len(x_test)):
    sum=sum+((x_test['Longitude'][i]-m)**2)
x=math.sqrt(sum)
z=SSE/(len(y_test)-3)
s=math.sqrt(z)
sb2=s/x
t=w2/sb2

In [273]:
t

10.009646350887325

In [274]:
t>=talpha

True

Hence we reject null hypothesis

# Hence we can conclude that Signal Strength does depend on Latitude and Longitude significantly.

In [172]:
#For download data speed there exists a significant relationship with latitude and longitude.
#For upload data speed there exists a significant relationship with latitude only.
#For signal strength also there exists a significant relationship with latitude and longitude.
