In [1]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
data=pd.read_csv("final_data.csv")
#final_data is the final pre processed data

In [2]:
data.head(5)

Operator In Out Travelling Network Type  Rating Call Drop Category  \
0    Airtel            Indoor           4G       3       Satisfactory   
1  Vodafone            Indoor           4G       1       Call Dropped   
2    Airtel            Indoor           3G       1       Call Dropped   
3    Airtel            Indoor           4G       3       Satisfactory   
4    Airtel        Travelling           4G       3       Satisfactory   

   Latitude  Longitude   State Name  Average Data Speed Download  \
0  0.196228   0.325356    Karnataka                     0.271480   
1  0.632907   0.135432      Gujarat                     0.211519   
2  0.127093   0.290671   Tamil Nadu                     0.036321   
3  0.580181   0.155327      Gujarat                     0.175517   
4  0.425737   0.180503  Maharashtra                     0.333021   

   Average Data Speed Upload  Population  Literacy Rate  Rainfall  \
0                   0.197512           2              7         3   
1                   0.370879           2              8         2   
2                   0.062303           2              8         2   
3                   0.191200           2              8         2   
4                   0.395612           4              8         4   

   Area of the state  Average_Signal  
0           0.504087        0.476721  
1           0.518040        0.477252  
2           0.300607        0.478454  
3           0.518040        0.477699  
4           0.886194        0.476859

In [81]:
data.count()[0]
#This gives the number of obkects in dataset

30715

In [82]:
from sklearn import preprocessing
from numpy.linalg import inv

In [83]:
X=data[['Latitude','Longitude']]
#Latitude and Longitude are the independent variables

In [84]:
X.count()

Latitude     30715
Longitude    30715
dtype: int64

In [85]:
y=data['Average_Signal']
#Signal Strength is the dependent variable

In [86]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
#We have used holdout method and 70%of data is taken as training data and rest as testing 

In [87]:
x_train.head()

Latitude  Longitude
0  0.498700   0.631606
1  0.451912   0.143607
2  0.871258   0.274259
3  0.594659   0.729902
4  0.193572   0.417718

In [88]:
n=x_train.count()[0]

In [89]:
n
#This is the number of objects in training data

21500

# Signal Strength Latitude Longitude Regression of degree 1

In [90]:
sum_x1=0
#sum_x1 means summation of x1 for all objects
sum_x2=0
#sum_x2 means summation of x2 for all objects
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
#The sums act as accumulator 
for i in range(0,n):
    sum_x1=sum_x1+x_train['Latitude'][i]
    sum_x2=sum_x2+x_train['Longitude'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Latitude'][i]*x_train['Latitude'][i]
    sum_x1x2=sum_x1x2+x_train['Latitude'][i]*x_train['Longitude'][i]
    sum_x2x2=sum_x2x2+x_train['Longitude'][i]*x_train['Longitude'][i]
    sum_x1y1=sum_x1y1+x_train['Latitude'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Longitude'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2)

In [91]:
A

array([[21500.        , 11305.59854537,  6946.46140205],
       [11305.59854537,  6825.95490532,  3754.38127528],
       [ 6946.46140205,  3754.38127528,  2972.37613929]])

In [92]:
B

array([10277.11947377,  5404.55831731,  3320.91843363])

In [93]:
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])

In [94]:
W
#W is the parameter array

array([4.77600305e-01, 4.07924288e-04, 5.90384020e-04])

In [95]:
y_pred=w0+w1*x_test['Latitude']+w2*x_test['Longitude']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE1=np.sqrt(MSE/len(y_test))
RMSE1
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.001040985302475305

# Signal Strength Latitude Longitude Regression of degree 2


In [96]:
sum_x1x1=0
#sum_x1x1 means summation of square of x1 for all objects
sum_x2x2=0
#sum_x2x2 means summation of square of x2 for all objects
sum_x1x2=0
#sum_x1x2 means summation of product of x1 and x2 for all objects
sum_x1=0
sum_x2=0
sum_x1x1x1x1=0
sum_x1x1x2x2=0
sum_x1x1x1x2=0
sum_x1x1x1=0
sum_x1x1x2=0
sum_x2x2=0
sum_x2x2x2x2=0
sum_x1x2x2x2=0
sum_x1x2x2=0
sum_x2x2x2=0
sum_y1=0
sum_x1x1y1=0
sum_x2x2y1=0
sum_x1x2y1=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_y1=sum_y1+y_train[i]
    sum_x1y1=sum_x1y1+x_train['Latitude'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Longitude'][i]*y_train[i]
    sum_x1x1y1=sum_x1x1y1+(x_train['Latitude'][i]**2)*y_train[i]
    sum_x2x2y1=sum_x2x2y1+(x_train['Longitude'][i]**2)*y_train[i]
    sum_x1x2y1=sum_x1x2y1+x_train['Latitude'][i]*x_train['Longitude'][i]*y_train[i]
    sum_x1=sum_x1+x_train['Latitude'][i]
    sum_x2=sum_x2+x_train['Longitude'][i]
    sum_x1x1=sum_x1x1+x_train['Latitude'][i]*x_train['Latitude'][i]
    sum_x1x2=sum_x1x2+x_train['Latitude'][i]*x_train['Longitude'][i]
    sum_x2x2=sum_x2x2+x_train['Longitude'][i]*x_train['Longitude'][i]
    sum_x1x1x1=sum_x1x1x1+(x_train['Latitude'][i])**3
    sum_x2x2x2=sum_x2x2x2+(x_train['Longitude'][i])**3
    sum_x1x1x2=sum_x1x1x2+((x_train['Latitude'][i])**2)*x_train['Longitude'][i]
    sum_x1x2x2=sum_x1x2x2+x_train['Latitude'][i]*(x_train['Longitude'][i])**2
    sum_x1x1x1x1=sum_x1x1x1x1+x_train['Latitude'][i]**4
    sum_x2x2x2x2=sum_x2x2x2x2+x_train['Longitude'][i]**4
    sum_x1x1x2x2=sum_x1x1x2x2+(x_train['Latitude'][i]*x_train['Longitude'][i])**2
    sum_x1x1x1x2=sum_x1x1x1x2+(x_train['Latitude'][i]**3)*x_train['Longitude'][i]
    sum_x1x2x2x2=sum_x1x2x2x2+x_train['Latitude'][i]*(x_train['Longitude'][i])**3
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2,w3,w4,w5)

In [97]:
A = np.array([[n, sum_x1x1, sum_x2x2,sum_x1x2,sum_x1,sum_x2], [sum_x1x1, sum_x1x1x1x1, sum_x1x1x2x2,sum_x1x1x1x2,sum_x1x1x1,sum_x1x1x2],[sum_x2x2,sum_x1x1x2x2,sum_x2x2x2x2,sum_x1x2x2x2,sum_x1x2x2,sum_x2x2x2],[sum_x1x2,sum_x1x1x1x2,sum_x1x2x2x2,sum_x1x1x2x2,sum_x1x1x2,sum_x1x2x2],[sum_x1,sum_x1x1x1,sum_x1x2x2,sum_x1x1x2,sum_x1x1,sum_x1x2],[sum_x2,sum_x1x1x2,sum_x2x2x2,sum_x1x2x2,sum_x1x2,sum_x2x2]]                                   )
B=np.array([sum_y1, sum_x1x1y1, sum_x2x2y1,sum_x1x2y1,sum_x1y1,sum_x2y1])

In [98]:
A

array([[21500.        ,  6825.95490532,  2972.37613929,  3754.38127528,
        11305.59854537,  6946.46140205],
       [ 6825.95490532,  3156.62435296,  1027.46998534,  1546.67331952,
         4499.52034424,  2319.52019583],
       [ 2972.37613929,  1027.46998534,   922.57426515,   892.38862712,
         1657.43453661,  1556.96804838],
       [ 3754.38127528,  1546.67331952,   892.38862712,  1027.46998534,
         2319.52019583,  1657.43453661],
       [11305.59854537,  4499.52034424,  1657.43453661,  2319.52019583,
         6825.95490532,  3754.38127528],
       [ 6946.46140205,  2319.52019583,  1556.96804838,  1657.43453661,
         3754.38127528,  2972.37613929]])

In [99]:
B

array([10277.11947377,  3263.02095782,  1421.22439484,  1794.97096953,
        5404.55831731,  3320.91843363])

In [100]:
Inverse=inv(A)

In [101]:
Inverse

array([[ 0.01004759,  0.01394779,  0.0125862 ,  0.02629619, -0.02369846,
        -0.02568816],
       [ 0.01394779,  0.03503786,  0.03038474,  0.01051099, -0.03997112,
        -0.03122798],
       [ 0.0125862 ,  0.03038474,  0.07955316, -0.02744103, -0.02340052,
        -0.04993752],
       [ 0.02629619,  0.01051099, -0.02744103,  0.15319246, -0.06055217,
        -0.06422192],
       [-0.02369846, -0.03997112, -0.02340052, -0.06055217,  0.06247713,
         0.05368311],
       [-0.02568816, -0.03122798, -0.04993752, -0.06422192,  0.05368311,
         0.07890105]])

In [102]:
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]+Inverse[0][3]*B[3]+Inverse[0][4]*B[4]+Inverse[0][5]*B[5]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]+Inverse[1][3]*B[3]+Inverse[1][4]*B[4]+Inverse[1][5]*B[5]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]+Inverse[2][3]*B[3]+Inverse[2][4]*B[4]+Inverse[2][5]*B[5]
w3=Inverse[3][0]*B[0]+Inverse[3][1]*B[1]+Inverse[3][2]*B[2]+Inverse[3][3]*B[3]+Inverse[3][4]*B[4]+Inverse[3][5]*B[5]
w4=Inverse[4][0]*B[0]+Inverse[4][1]*B[1]+Inverse[4][2]*B[2]+Inverse[4][3]*B[3]+Inverse[4][4]*B[4]+Inverse[4][5]*B[5]
w5=Inverse[5][0]*B[0]+Inverse[5][1]*B[1]+Inverse[5][2]*B[2]+Inverse[5][3]*B[3]+Inverse[5][4]*B[4]+Inverse[5][5]*B[5]
W=np.array([w0,w1,w2,w3,w4,w5])
#Matrix multiplication gives w0,w1,w2,w3,w4,w5

In [103]:
W

array([ 0.47296749, -0.00903213, -0.00496578, -0.01059884,  0.01325304,
        0.01075223])

In [110]:
y_pred=w0+w1*x_test['Latitude']**2+w2*x_test['Longitude']**2+w3*x_test['Latitude']*x_test['Longitude']+w4*x_test['Latitude']+w5*x_test['Longitude']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE2=np.sqrt(MSE/len(y_test))
RMSE2
#RMSE value for model 2 is also found

0.0009738926926944041

In [111]:
RMSE1-RMSE2
#RMSE value for both models are almost same
#RMSE are the root mean square errors for models of degree 1 and degree 2

6.709260978090084e-05