In [63]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
data=pd.read_csv("final_data.csv")
#final_data is the final pre processed data

In [64]:
data.head(5)

Operator In Out Travelling Network Type  Rating Call Drop Category  \
0    Airtel            Indoor           4G       3       Satisfactory   
1  Vodafone            Indoor           4G       1       Call Dropped   
2    Airtel            Indoor           3G       1       Call Dropped   
3    Airtel            Indoor           4G       3       Satisfactory   
4    Airtel        Travelling           4G       3       Satisfactory   

   Latitude  Longitude   State Name  Average Data Speed Download  \
0  0.196228   0.325356    Karnataka                     0.271480   
1  0.632907   0.135432      Gujarat                     0.211519   
2  0.127093   0.290671   Tamil Nadu                     0.036321   
3  0.580181   0.155327      Gujarat                     0.175517   
4  0.425737   0.180503  Maharashtra                     0.333021   

   Average Data Speed Upload  Population  Literacy Rate  Rainfall  \
0                   0.197512           2              7         3   
1                   0.370879           2              8         2   
2                   0.062303           2              8         2   
3                   0.191200           2              8         2   
4                   0.395612           4              8         4   

   Area of the state  Average_Signal  
0           0.504087        0.476721  
1           0.518040        0.477252  
2           0.300607        0.478454  
3           0.518040        0.477699  
4           0.886194        0.476859

In [65]:
data.count()[0]

30715

In [66]:
from sklearn import preprocessing
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression

In [67]:
X=data[['Average Data Speed Download','Average Data Speed Upload']]

In [68]:
X.count()

Average Data Speed Download    30715
Average Data Speed Upload      30715
dtype: int64

In [69]:
y=data['Average_Signal']

In [70]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
#We have used holdout method and 70%of data is taken as training data and rest as testing 

In [71]:
x_train.head()

Average Data Speed Download  Average Data Speed Upload
0                     0.970965                   0.556211
1                     0.333021                   0.395612
2                     0.077017                   0.105498
3                     0.058113                   0.079079
4                     0.036321                   0.062303

In [72]:
n=x_train.count()[0]

In [73]:
n

21500

# Regression of degree 1

In [79]:
sum_x1=0
#sum_x1 means summation of x1 for all objects
sum_x2=0
#sum_x2 means summation of x2 for all objects
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
#The sums act as accumulator
for i in range(0,n):
    sum_x1=sum_x1+x_train['Average Data Speed Download'][i]
    sum_x2=sum_x2+x_train['Average Data Speed Upload'][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Download'][i]
    sum_x1x2=sum_x1x2+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Upload'][i]
    sum_x2x2=sum_x2x2+x_train['Average Data Speed Upload'][i]*x_train['Average Data Speed Upload'][i]
    sum_x1y1=sum_x1y1+x_train['Average Data Speed Download'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Average Data Speed Upload'][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2)

In [80]:
A

array([[21500.        ,  8869.84387229,  6666.07773408],
       [ 8869.84387229,  5563.8053476 ,  3501.17154422],
       [ 6666.07773408,  3501.17154422,  2675.80122501]])

In [81]:
B

array([10277.11947448,  4242.56826363,  3186.33117946])

In [82]:
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])

In [83]:
W

array([ 0.47796416,  0.00290922, -0.00373748])

In [85]:
y_pred=w0+w1*x_test['Average Data Speed Download']+w2*x_test['Average Data Speed Upload']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE1=np.sqrt(MSE/len(y_test))
RMSE1
#RMSE is used to find the goodness of the model and is calacuated as root of sum of square of difference of actual and prediacted values.

0.0008458361122832141

In [86]:
ybar=y_test.mean()
ybar

0.4780193570691356

In [87]:
SSR=0
SST=0
SSE=0
y_test.count()

9215

In [88]:
for i in range (0,len(y_test)):
    SST=SST+(y_test[i]-ybar)*(y_test[i]-ybar)
    SSR=SSR+(y_pred[i]-ybar)*(y_pred[i]-ybar)
    SSE=SSE+(y_test[i]-y_pred[i])*(y_test[i]-y_pred[i])  

In [89]:
print("Total sum of squares=", SST )

Total sum of squares= 0.010176870687435726


In [90]:
print("Sum of squares due to regression =", SSR)

Sum of squares due to regression = 0.0035240283138003882


In [91]:
print("Sum of square due to error=", SSE)

Sum of square due to error= 0.006592767886282549


In [92]:
Rsquare=SSR/SST

In [93]:
print("R square value=",Rsquare)

R square value= 0.3462781853120255


Since there are 2 independent variable so R square adjusted is also calculated. 

In [95]:
p=2
n=len(y_test)
len(x_train)+len(x_test)
Rsquare_adjusted=1-(((1-Rsquare)*(n-1))/(n-p-1))
Rsquare_adjusted

0.3461362569979378

# Regression of degree 2


In [43]:
sum_x1x1=0
sum_x2x2=0
sum_x1x2=0
sum_x1=0
sum_x2=0
sum_x1x1x1x1=0
sum_x1x1x2x2=0
sum_x1x1x1x2=0
sum_x1x1x1=0
sum_x1x1x2=0
sum_x2x2=0
sum_x2x2x2x2=0
sum_x1x2x2x2=0
sum_x1x2x2=0
sum_x2x2x2=0
sum_y1=0
sum_x1x1y1=0
sum_x2x2y1=0
sum_x1x2y1=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_y1=sum_y1+y_train[i]
    sum_x1y1=sum_x1y1+x_train['Average Data Speed Download'][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train['Average Data Speed Upload'][i]*y_train[i]
    sum_x1x1y1=sum_x1x1y1+(x_train['Average Data Speed Download'][i]**2)*y_train[i]
    sum_x2x2y1=sum_x2x2y1+(x_train['Average Data Speed Upload'][i]**2)*y_train[i]
    sum_x1x2y1=sum_x1x2y1+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Upload'][i]*y_train[i]
    sum_x1=sum_x1+x_train['Average Data Speed Download'][i]
    sum_x2=sum_x2+x_train['Average Data Speed Upload'][i]
    sum_x1x1=sum_x1x1+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Download'][i]
    sum_x1x2=sum_x1x2+x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Upload'][i]
    sum_x2x2=sum_x2x2+x_train['Average Data Speed Upload'][i]*x_train['Average Data Speed Upload'][i]
    sum_x1x1x1=sum_x1x1x1+(x_train['Average Data Speed Download'][i])**3
    sum_x2x2x2=sum_x2x2x2+(x_train['Average Data Speed Upload'][i])**3
    sum_x1x1x2=sum_x1x1x2+((x_train['Average Data Speed Download'][i])**2)*x_train['Average Data Speed Upload'][i]
    sum_x1x2x2=sum_x1x2x2+x_train['Average Data Speed Download'][i]*(x_train['Average Data Speed Upload'][i])**2
    sum_x1x1x1x1=sum_x1x1x1x1+x_train['Average Data Speed Download'][i]**4
    sum_x2x2x2x2=sum_x2x2x2x2+x_train['Average Data Speed Upload'][i]**4
    sum_x1x1x2x2=sum_x1x1x2x2+(x_train['Average Data Speed Download'][i]*x_train['Average Data Speed Upload'][i])**2
    sum_x1x1x1x2=sum_x1x1x1x2+(x_train['Average Data Speed Download'][i]**3)*x_train['Average Data Speed Upload'][i]
    sum_x1x2x2x2=sum_x1x2x2x2+x_train['Average Data Speed Download'][i]*(x_train['Average Data Speed Upload'][i])**3
#All the sums are used to calculate A and then X is calculated using AX=B so X=Inverse(A)*B 
#X will give all the parameters(w0,w1,w2,w3,w4,w5)

In [44]:
A = np.array([[n, sum_x1x1, sum_x2x2,sum_x1x2,sum_x1,sum_x2], [sum_x1x1, sum_x1x1x1x1, sum_x1x1x2x2,sum_x1x1x1x2,sum_x1x1x1,sum_x1x1x2],[sum_x2x2,sum_x1x1x2x2,sum_x2x2x2x2,sum_x1x2x2x2,sum_x1x2x2,sum_x2x2x2],[sum_x1x2,sum_x1x1x1x2,sum_x1x2x2x2,sum_x1x1x2x2,sum_x1x1x2,sum_x1x2x2],[sum_x1,sum_x1x1x1,sum_x1x2x2,sum_x1x1x2,sum_x1x1,sum_x1x2],[sum_x2,sum_x1x1x2,sum_x2x2x2,sum_x1x2x2,sum_x1x2,sum_x2x2]]                                   )
B=np.array([sum_y1, sum_x1x1y1, sum_x2x2y1,sum_x1x2y1,sum_x1y1,sum_x2y1])

In [45]:
A

array([[9215.        , 2355.7696989 , 1147.49839786, 1489.18632923,
        3774.2583066 , 2852.99232028],
       [2355.7696989 , 1402.03907431,  471.49306303,  787.38584488,
        1739.59139959, 1013.99251932],
       [1147.49839786,  471.49306303,  283.0158802 ,  323.79933038,
         661.04773487,  536.32903071],
       [1489.18632923,  787.38584488,  323.79933038,  471.49306303,
        1013.99251932,  661.04773487],
       [3774.2583066 , 1739.59139959,  661.04773487, 1013.99251932,
        2355.7696989 , 1489.18632923],
       [2852.99232028, 1013.99251932,  536.32903071,  661.04773487,
        1489.18632923, 1147.49839786]])

In [46]:
B

array([4404.79482412, 1127.57293896,  548.54268934,  712.46696396,
       1805.24294288, 1363.67644629])

In [47]:
Inverse=inv(A)

In [48]:
Inverse

array([[ 1.02722270e-03,  1.52647733e-03,  6.38398881e-03,
        -1.90413471e-03, -4.72236994e-04, -5.17686194e-03],
       [ 1.52647733e-03,  1.30172521e-01,  1.49244936e-01,
        -3.01479905e-01, -7.03091415e-03, -5.77816275e-03],
       [ 6.38398881e-03,  1.49244936e-01,  3.53760386e-01,
        -4.73440414e-01,  5.33961687e-02, -1.09654894e-01],
       [-1.90413471e-03, -3.01479905e-01, -4.73440414e-01,
         8.44487248e-01, -4.85142691e-02,  6.88899368e-02],
       [-4.72236994e-04, -7.03091415e-03,  5.33961687e-02,
        -4.85142691e-02,  3.17946091e-02, -3.08838618e-02],
       [-5.17686194e-03, -5.77816275e-03, -1.09654894e-01,
         6.88899368e-02, -3.08838618e-02,  7.04941748e-02]])

In [49]:
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]+Inverse[0][3]*B[3]+Inverse[0][4]*B[4]+Inverse[0][5]*B[5]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]+Inverse[1][3]*B[3]+Inverse[1][4]*B[4]+Inverse[1][5]*B[5]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]+Inverse[2][3]*B[3]+Inverse[2][4]*B[4]+Inverse[2][5]*B[5]
w3=Inverse[3][0]*B[0]+Inverse[3][1]*B[1]+Inverse[3][2]*B[2]+Inverse[3][3]*B[3]+Inverse[3][4]*B[4]+Inverse[3][5]*B[5]
w4=Inverse[4][0]*B[0]+Inverse[4][1]*B[1]+Inverse[4][2]*B[2]+Inverse[4][3]*B[3]+Inverse[4][4]*B[4]+Inverse[4][5]*B[5]
w5=Inverse[5][0]*B[0]+Inverse[5][1]*B[1]+Inverse[5][2]*B[2]+Inverse[5][3]*B[3]+Inverse[5][4]*B[4]+Inverse[5][5]*B[5]
W=np.array([w0,w1,w2,w3,w4,w5])

In [50]:
W

array([ 0.47910987,  0.0035244 ,  0.00599093,  0.00262503, -0.00131297,
       -0.00852914])

In [58]:
y_pred=w0+w1*x_test['Average Data Speed Download']**2+w2*x_test['Average Data Speed Upload']**2+w3*x_test['Average Data Speed Download']*x_test['Average Data Speed Upload']+w4*x_test['Average Data Speed Download']+w5*x_test['Average Data Speed Upload']
#y_pred gives the predicted values of y based on the regression model
MSE=0
for i in range(0,len(y_test)):
    MSE=MSE+(y_pred[i]-y_test[i])**2
RMSE2=np.sqrt(MSE/len(y_test))
RMSE2
#RMSE value for model 2 is also found

0.0006381727077724021

In [60]:
RMSE1-RMSE2

0.000814128804272984